name: kiltedbroker
favicon: null
layout_spectrum: 0.9253149423748255
typography_spectrum: 0.33355573611333966
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.014492630492895842
  lightness: 0.17682244814932346
  saturation: 0.047816789243370295
  rhythmicContrast: 0.9869762205053121
purpose: []
